//
//  Collection.swift
//  NeoDBKit
//
//  Created by 甜檸Citron(lcandy2) on 10/12/25.
//  Copyright © 2025 https://github.com/lcandy2. All Rights Reserved.
//

import Foundation

/// Represents a user-defined collection of items in NeoDB.
///
/// A collection has its own visibility, metadata, and presentation content,
/// and can contain multiple items. This model mirrors the server payload
/// and is suitable for rendering and editing within the app.
public struct Collection: CollectionProtocol {
    /// Unique identifier of the collection.
    public let uuid: CollectionAttributes.UUID
    /// Public URL to view this collection on the web.
    public let url: CollectionAttributes.URL
    /// API endpoint URL for this collection, if available.
    public let apiUrl: CollectionAttributes.ApiURL?
    /// Visibility of the collection (e.g., public, unlisted, private).
    public var visibility: NeoDBVisibility
    /// Associated post identifier (if federated to a social network).
    public let postId: Int?
    /// Creation timestamp on the server.
    public let createdTime: ServerDate
    /// Title of the collection.
    public var title: String
    /// Short description or summary of the collection.
    public var brief: String
    /// Cover image URL for the collection.
    public var coverImageUrl: CollectionAttributes.CoverImageURL? = nil
    /// HTML content describing the collection in rich text.
    public let htmlContent: HTMLString
    /// Whether the collection is dynamically generated by the server.
    public var isDynamic: Bool = false

    /// Stable identifier for UI usage (aliases `uuid`).
    public var id: String { uuid }

    @available(*, deprecated, message: "Use `coverImageUrl` instead")
    /// Deprecated. Use `coverImageUrl` for the cover image reference.
    public var cover: CollectionAttributes.Cover? = nil
}

extension Collection {
    /// Converts this model to a `CollectionIn` payload suitable for create/update.
    /// - Returns: A `CollectionIn` with fields derived from the current instance.
    public func toCollectionIn() -> CollectionIn {
        CollectionIn(brief: self.brief, title: self.title, visibility: self.visibility)
    }
}
